name: cicd

on:
  push:
    branches: [ "main" ]

jobs:
  murun-cicd:
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: gradle

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      - name: Grant execute permission gradlew
        run: chmod +x gradlew

      - name: gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        
      - name: Test
        run: ./gradlew test
        
      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/
      
      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy
      
      # deploy.sh 파일 복사
      - name: Copy deploy.sh
        run: cp deploy.sh ./deploy
        
      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./murun.zip ./deploy
        working-directory: ${{env.working-directory}}
        
      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp --region ap-northeast-2 --acl private ./murun.zip s3://$AWS_S3_BUCKET
          
    # 배포
      - name: CodeDeploy
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
            --application-name murun \
            --deployment-group-name murun-deploy \
            --s3-location bucket=$AWS_S3_BUCKET,key=murun.zip,bundleType=zip \
            --region us-east-1
